spring:
  datasource:
    url: jdbc:mysql://localhost:3306/generator_kotlin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 930919
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update